version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" 
      - "4510:4510" 
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  awscli:
    image: amazon/aws-cli
    container_name: awscli
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ~/.aws:/root/.aws  
    depends_on:
      - localstack

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./terraform:/workspace 
    depends_on:
      - localstack

volumes:
  localstack_data:
